services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    volumes:
      - .tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: glideapp_database
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
